package Form;
import LoginAdmin.login;
import LoginAdmin.login;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Panel;
import java.awt.event.ActionListener;
import javax.swing.JPanel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 002
 */
public class MenuUtama extends javax.swing.JFrame {
    
    /**
     * Creates new form menu
     */
    Timer timer;
    Color hoverButton;
    private Connection conn = new koneksi().connect();
    
    public MenuUtama() {
        initComponents();
        setVisible(true);
        
        sliderMenuDefault();
        
        JamTanggal();
        this.hoverButton = form.getBackground();
       
        
    }
    
    // untuk sliderMenu
    private void sliderMenuDefault(){
        slideMenuForm.setVisible(false);
        slideMenuTransaksi.setVisible(false);
        slideMenuLaporan.setVisible(false);
    }
    
    private void hiddenSubMenu(){
        if(slideMenuForm.isVisible() == true){
            slideMenuForm.setVisible(false);
        }
        if(slideMenuTransaksi.isVisible() == true){
            slideMenuTransaksi.setVisible(false);
        }
        if(slideMenuLaporan.isVisible() == true){
            slideMenuLaporan.setVisible(false);
        }
    }
    
    private void showSubMenu(JPanel subMenu){
        if(subMenu.isVisible() == false){
            hiddenSubMenu();
            subMenu.setVisible(true);
        }else{
            subMenu.setVisible(false);
        }
    }
    //akhis slider menu
    
    //clock
    private void JamTanggal(){
        ActionListener actionListener = new ActionListener(){
           @Override
            public void actionPerformed(ActionEvent e) {
                //Time in 24Hrs Format
                Date date = new Date();
                DateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
                String time = timeFormat.format(date);
                clock.setText(time);
                //Todays Date
                Date date2 = new Date();
                DateFormat timeFormat2 = new SimpleDateFormat("dd/MM/yyyy");
                String time2 = timeFormat2.format(date2);
                tanggal.setText(time2);
           }     
        };
        timer = new Timer(1000, actionListener);
        timer.setInitialDelay(0);
        timer.start();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDashboard = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        Panel2 = new javax.swing.JPanel();
        dashboard = new javax.swing.JLabel();
        transaksi = new javax.swing.JLabel();
        laporan = new javax.swing.JLabel();
        slideMenuForm = new javax.swing.JPanel();
        menuGuru = new javax.swing.JLabel();
        menuSiswa = new javax.swing.JLabel();
        menuKelas = new javax.swing.JLabel();
        menuPelajaran = new javax.swing.JLabel();
        menuAbsen = new javax.swing.JLabel();
        slideMenuTransaksi = new javax.swing.JPanel();
        menuNilai = new javax.swing.JLabel();
        slideMenuLaporan = new javax.swing.JPanel();
        menuReportGuru = new javax.swing.JLabel();
        menuReportSiswa = new javax.swing.JLabel();
        menuReportAbsen = new javax.swing.JLabel();
        menuReportPelajaran = new javax.swing.JLabel();
        menuReportNilai = new javax.swing.JLabel();
        form = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        MenuLogo = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        judul1 = new javax.swing.JLabel();
        judul2 = new javax.swing.JLabel();
        Pane = new javax.swing.JPanel();
        Panel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        clock = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mMaster = new javax.swing.JMenu();
        formGuru = new javax.swing.JMenuItem();
        formSiswa = new javax.swing.JMenuItem();
        formPelajaran = new javax.swing.JMenuItem();
        formKelas = new javax.swing.JMenuItem();
        formAbsen = new javax.swing.JMenuItem();
        Transaksi = new javax.swing.JMenu();
        transNilai = new javax.swing.JMenuItem();
        Laporan = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1600, 900));
        setMinimumSize(new java.awt.Dimension(1000, 620));
        setSize(new java.awt.Dimension(0, 0));

        PanelDashboard.setBackground(new java.awt.Color(255, 51, 51));
        PanelDashboard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        PanelDashboard.setMaximumSize(new java.awt.Dimension(1500, 700));
        PanelDashboard.setMinimumSize(new java.awt.Dimension(950, 520));
        PanelDashboard.setPreferredSize(new java.awt.Dimension(1100, 590));

        Menu.setBackground(new java.awt.Color(255, 51, 51));
        Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Menu.setMaximumSize(new java.awt.Dimension(32767, 600));

        Panel2.setBackground(new java.awt.Color(255, 51, 51));
        Panel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        dashboard.setBackground(new java.awt.Color(255, 51, 51));
        dashboard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboard.setText("  Dashboard");
        dashboard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dashboard.setOpaque(true);
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardMouseExited(evt);
            }
        });

        transaksi.setBackground(new java.awt.Color(255, 51, 51));
        transaksi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        transaksi.setForeground(new java.awt.Color(255, 255, 255));
        transaksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transaksi.setText("  Transaksi");
        transaksi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        transaksi.setOpaque(true);
        transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transaksiMouseExited(evt);
            }
        });

        laporan.setBackground(new java.awt.Color(255, 51, 51));
        laporan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        laporan.setForeground(new java.awt.Color(255, 255, 255));
        laporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laporan.setText("  Laporan");
        laporan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        laporan.setOpaque(true);
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanMouseExited(evt);
            }
        });

        slideMenuForm.setBackground(new java.awt.Color(255, 255, 255));

        menuGuru.setBackground(new java.awt.Color(255, 255, 255));
        menuGuru.setText("       Guru");
        menuGuru.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuGuru.setOpaque(true);
        menuGuru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuGuruMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuGuruMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuGuruMouseExited(evt);
            }
        });

        menuSiswa.setBackground(new java.awt.Color(255, 255, 255));
        menuSiswa.setText("       Siswa");
        menuSiswa.setOpaque(true);
        menuSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSiswaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuSiswaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuSiswaMouseExited(evt);
            }
        });

        menuKelas.setBackground(new java.awt.Color(255, 255, 255));
        menuKelas.setText("       Kelas      ");
        menuKelas.setOpaque(true);
        menuKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuKelasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuKelasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuKelasMouseExited(evt);
            }
        });

        menuPelajaran.setBackground(new java.awt.Color(255, 255, 255));
        menuPelajaran.setText("       Pelajaran");
        menuPelajaran.setOpaque(true);
        menuPelajaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPelajaranMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuPelajaranMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuPelajaranMouseExited(evt);
            }
        });

        menuAbsen.setBackground(new java.awt.Color(255, 255, 255));
        menuAbsen.setText("       Absen");
        menuAbsen.setOpaque(true);
        menuAbsen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAbsenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuAbsenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuAbsenMouseExited(evt);
            }
        });

        javax.swing.GroupLayout slideMenuFormLayout = new javax.swing.GroupLayout(slideMenuForm);
        slideMenuForm.setLayout(slideMenuFormLayout);
        slideMenuFormLayout.setHorizontalGroup(
            slideMenuFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuPelajaran, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
            .addComponent(menuAbsen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slideMenuFormLayout.setVerticalGroup(
            slideMenuFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slideMenuFormLayout.createSequentialGroup()
                .addComponent(menuGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuPelajaran, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuAbsen, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        slideMenuTransaksi.setBackground(new java.awt.Color(255, 255, 255));

        menuNilai.setBackground(new java.awt.Color(255, 255, 255));
        menuNilai.setText("       Nilai");
        menuNilai.setOpaque(true);
        menuNilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuNilaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuNilaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuNilaiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout slideMenuTransaksiLayout = new javax.swing.GroupLayout(slideMenuTransaksi);
        slideMenuTransaksi.setLayout(slideMenuTransaksiLayout);
        slideMenuTransaksiLayout.setHorizontalGroup(
            slideMenuTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 223, Short.MAX_VALUE)
            .addGroup(slideMenuTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(menuNilai, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
        );
        slideMenuTransaksiLayout.setVerticalGroup(
            slideMenuTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
            .addGroup(slideMenuTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(slideMenuTransaksiLayout.createSequentialGroup()
                    .addComponent(menuNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );

        slideMenuLaporan.setBackground(new java.awt.Color(255, 255, 255));

        menuReportGuru.setBackground(new java.awt.Color(255, 255, 255));
        menuReportGuru.setText("       Laporan Data Guru");
        menuReportGuru.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuReportGuru.setOpaque(true);
        menuReportGuru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuReportGuruMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuReportGuruMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuReportGuruMouseExited(evt);
            }
        });

        menuReportSiswa.setBackground(new java.awt.Color(255, 255, 255));
        menuReportSiswa.setText("       Laporan Data Siswa");
        menuReportSiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuReportSiswa.setOpaque(true);
        menuReportSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuReportSiswaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuReportSiswaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuReportSiswaMouseExited(evt);
            }
        });

        menuReportAbsen.setBackground(new java.awt.Color(255, 255, 255));
        menuReportAbsen.setText("       Laporan Data Absen");
        menuReportAbsen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuReportAbsen.setOpaque(true);
        menuReportAbsen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuReportAbsenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuReportAbsenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuReportAbsenMouseExited(evt);
            }
        });

        menuReportPelajaran.setBackground(new java.awt.Color(255, 255, 255));
        menuReportPelajaran.setText("       Laporan Data Mata Pelajaran");
        menuReportPelajaran.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuReportPelajaran.setOpaque(true);
        menuReportPelajaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuReportPelajaranMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuReportPelajaranMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuReportPelajaranMouseExited(evt);
            }
        });

        menuReportNilai.setBackground(new java.awt.Color(255, 255, 255));
        menuReportNilai.setText("       Laporan Data Nilai");
        menuReportNilai.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuReportNilai.setOpaque(true);
        menuReportNilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuReportNilaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuReportNilaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuReportNilaiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout slideMenuLaporanLayout = new javax.swing.GroupLayout(slideMenuLaporan);
        slideMenuLaporan.setLayout(slideMenuLaporanLayout);
        slideMenuLaporanLayout.setHorizontalGroup(
            slideMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuReportGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuReportSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuReportAbsen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuReportPelajaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuReportNilai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slideMenuLaporanLayout.setVerticalGroup(
            slideMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slideMenuLaporanLayout.createSequentialGroup()
                .addComponent(menuReportGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuReportSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuReportAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuReportPelajaran, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuReportNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        form.setBackground(new java.awt.Color(255, 51, 51));
        form.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        form.setForeground(new java.awt.Color(255, 255, 255));
        form.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        form.setText("  Form");
        form.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        form.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        form.setOpaque(true);
        form.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        form.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
            .addComponent(transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(slideMenuLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(slideMenuTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(slideMenuForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(form, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(form, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slideMenuForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slideMenuTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slideMenuLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("  Log Out");
        logout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logout.setOpaque(true);
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MenuLogo.setBackground(new java.awt.Color(255, 51, 51));
        MenuLogo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        logo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo.jpg"))); // NOI18N

        judul1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        judul1.setForeground(new java.awt.Color(255, 255, 255));
        judul1.setText("Sistem Akademik");

        judul2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        judul2.setForeground(new java.awt.Color(255, 255, 255));
        judul2.setText("SDIT ISLAM NUR MURIA");

        javax.swing.GroupLayout MenuLogoLayout = new javax.swing.GroupLayout(MenuLogo);
        MenuLogo.setLayout(MenuLogoLayout);
        MenuLogoLayout.setHorizontalGroup(
            MenuLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLogoLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(MenuLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(judul1)
                    .addComponent(logo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLogoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(judul2)
                .addGap(22, 22, 22))
        );
        MenuLogoLayout.setVerticalGroup(
            MenuLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLogoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(judul1)
                .addGap(11, 11, 11)
                .addComponent(judul2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Pane.setBackground(new java.awt.Color(255, 255, 255));
        Pane.setMaximumSize(new java.awt.Dimension(1200, 650));
        Pane.setMinimumSize(new java.awt.Dimension(380, 200));
        Pane.setPreferredSize(new java.awt.Dimension(600, 570));
        Pane.setLayout(new java.awt.CardLayout());

        Panel3.setBackground(new java.awt.Color(255, 255, 255));
        Panel3.setMinimumSize(new java.awt.Dimension(950, 650));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("  Dashboard");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 0, new java.awt.Color(51, 51, 51)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 4, true));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/img2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setText("SDIT NUR MURIA ");

        jLabel2.setText("Jl. Raya Citayam Palabali RT 011/006, Bojong Pondok Terong, Kec. Cipayung, Kota Depok Prov. Jawa Barat");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 4, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clock.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clock.setForeground(new java.awt.Color(255, 255, 255));
        clock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(clock, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 190, 44));

        tanggal.setForeground(new java.awt.Color(255, 255, 255));
        tanggal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 116, 44));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/clockz.jpg"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 110));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 4, true));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Detail Sekolah");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel40.setText("Akreditasi : B ");

        jLabel41.setText("Kepala Sekolah : Poniran Ahmad Sulhan, S.Pd.I");

        jLabel42.setText("Operator :  Nurhadi, S. Pd.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel40))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel41)
                .addGap(30, 30, 30)
                .addComponent(jLabel42)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 4, true));

        jLabel4.setText("Guru : 11");

        jLabel5.setText("Siswa Laki - laki : 146");

        jLabel6.setText("Siswa Perempuan : 150");

        jLabel7.setText("Rombongan Belajar : 10");

        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0, new java.awt.Color(0, 0, 0)));

        jLabel10.setText("Kurikulum : SD 2013");

        jLabel11.setText("Penyelengaraan : Sehari Penuh/5 hari");

        jLabel12.setText("Manajemen Berbasis Sekolah : Ya");

        jLabel13.setText("Semester Data : 2020/2021-2");

        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0, new java.awt.Color(0, 0, 0)));

        jLabel30.setText("Sumber Listrik : PLN");

        jLabel31.setText("Akses Internet : Telkom Speedy");

        jLabel32.setText("Daya Listrik : 6,000");

        jLabel33.setText("Luas Tanah : 1M²");

        jLabel34.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0, new java.awt.Color(0, 0, 0)));

        jLabel35.setText("Laboratorium : 0 *");

        jLabel36.setText("Ruang Kelas : 30 *");

        jLabel37.setText("Perpustakaan : 3 *");

        jLabel38.setText("Sanitasi Siswa : 5 *");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel38))
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel33))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel43.setText("Copyright . Ver.1.0");

        javax.swing.GroupLayout Panel3Layout = new javax.swing.GroupLayout(Panel3);
        Panel3.setLayout(Panel3Layout);
        Panel3Layout.setHorizontalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(Panel3Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(Panel3Layout.createSequentialGroup()
                                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(Panel3Layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel43)))
                .addContainerGap())
        );
        Panel3Layout.setVerticalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 19, Short.MAX_VALUE)
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel43)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        Pane.add(Panel3, "card2");

        javax.swing.GroupLayout PanelDashboardLayout = new javax.swing.GroupLayout(PanelDashboard);
        PanelDashboard.setLayout(PanelDashboardLayout);
        PanelDashboardLayout.setHorizontalGroup(
            PanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MenuLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pane, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelDashboardLayout.setVerticalGroup(
            PanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelDashboardLayout.createSequentialGroup()
                        .addComponent(MenuLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        mMaster.setText("Form");

        formGuru.setText("Form Guru");
        formGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formGuruActionPerformed(evt);
            }
        });
        mMaster.add(formGuru);

        formSiswa.setText("Form Siswa");
        formSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formSiswaActionPerformed(evt);
            }
        });
        mMaster.add(formSiswa);

        formPelajaran.setText("Form Pelajaran");
        formPelajaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formPelajaranActionPerformed(evt);
            }
        });
        mMaster.add(formPelajaran);

        formKelas.setText("Form Kelas");
        formKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formKelasActionPerformed(evt);
            }
        });
        mMaster.add(formKelas);

        formAbsen.setText("Form Absen");
        formAbsen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formAbsenMouseClicked(evt);
            }
        });
        formAbsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formAbsenActionPerformed(evt);
            }
        });
        mMaster.add(formAbsen);

        jMenuBar1.add(mMaster);

        Transaksi.setText("Transaksi");

        transNilai.setText("Nilai");
        transNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transNilaiActionPerformed(evt);
            }
        });
        Transaksi.add(transNilai);

        jMenuBar1.add(Transaksi);

        Laporan.setText("Laporan");
        jMenuBar1.add(Laporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formGuruActionPerformed
        // TODO add your handling code here:
   
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();
        
        //add Panel, add panel dari Guru.Java (sebuah panel)
        Pane.add(new Guru());
        Pane.repaint();
        Pane.revalidate();
        
    }//GEN-LAST:event_formGuruActionPerformed

    private void formSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formSiswaActionPerformed
        // TODO add your handling code here:
   
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();
        
        //add Panel, add panel dari Siswa.Java (sebuah panel)
        Pane.add(new Siswa());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_formSiswaActionPerformed

    private void formPelajaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formPelajaranActionPerformed
        // TODO add your handling code here:
 
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();
        
        //add Panel, add panel dari Pelajaran.Java (sebuah panel)
        Pane.add(new Pelajaran());
        Pane.repaint();
        Pane.revalidate();
     
    }//GEN-LAST:event_formPelajaranActionPerformed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new login().setVisible(true);

    }//GEN-LAST:event_logoutMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:

        showSubMenu(slideMenuForm);
    }//GEN-LAST:event_formMouseClicked

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        // TODO add your handling code here:
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();
        
        //add Panel, add panel dari Siswa.Java (sebuah panel)
        Pane.add(Panel3);
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_dashboardMouseClicked

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseMoved

    private void menuGuruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuGuruMouseClicked
        // TODO add your handling code here:   
   
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();
        
        //add Panel, add panel dari Guru.Java (sebuah panel) 
        Pane.add(new Guru());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_menuGuruMouseClicked

    private void menuSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSiswaMouseClicked
        // TODO add your handling code here:

        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();
        
        //add Panel, add panel dari Guru.Java (sebuah panel)
        Pane.add(new Siswa());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_menuSiswaMouseClicked

    private void menuKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuKelasMouseClicked
        // TODO add your handling code here:
   
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();
        
        //add Panel, add panel dari Guru.Java (sebuah panel)        
        Pane.add(new Kelas());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_menuKelasMouseClicked

    private void menuPelajaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPelajaranMouseClicked
        // TODO add your handling code here
    
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();
        
        //add Panel, add panel dari Guru.Java (sebuah panel)
        Pane.add(new Pelajaran());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_menuPelajaranMouseClicked

    private void menuAbsenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAbsenMouseClicked
        // TODO add your handling code here:
     
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();
        
        //add Panel, add panel dari Guru.Java (sebuah panel)
        Pane.add(new Absen());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_menuAbsenMouseClicked

    private void formKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formKelasActionPerformed
        // TODO add your handling code here:
       
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();
        
        //add Panel, add panel dari Guru.Java (sebuah panel)        
        Pane.add(new Kelas());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_formKelasActionPerformed

    private void formAbsenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formAbsenMouseClicked
       
    }//GEN-LAST:event_formAbsenMouseClicked

    private void transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMouseClicked
        // TODO add your handling code here:
        showSubMenu(slideMenuTransaksi);
    }//GEN-LAST:event_transaksiMouseClicked

    private void laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseClicked
        // TODO add your handling code here:
        showSubMenu(slideMenuLaporan);
    }//GEN-LAST:event_laporanMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        form.setBackground(new Color(255,77,77));
        form.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        form.setBackground(hoverButton);
    }//GEN-LAST:event_formMouseExited

    private void transaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMouseEntered
        // TODO add your handling code here:
        transaksi.setBackground(new Color(255,77,77));
        transaksi.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_transaksiMouseEntered

    private void transaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMouseExited
        // TODO add your handling code here:
        transaksi.setBackground(hoverButton);
    }//GEN-LAST:event_transaksiMouseExited

    private void laporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseEntered
        // TODO add your handling code here:
        laporan.setBackground(new Color(255,77,77));
        laporan.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_laporanMouseEntered

    private void laporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseExited
        // TODO add your handling code here:
        laporan.setBackground(hoverButton);
    }//GEN-LAST:event_laporanMouseExited

    private void dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseEntered
        // TODO add your handling code here:
        dashboard.setBackground(new Color(255,77,77));
        dashboard.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_dashboardMouseEntered

    private void dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseExited
        // TODO add your handling code here:
        dashboard.setBackground(hoverButton);
    }//GEN-LAST:event_dashboardMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        logout.setBackground(new Color(255,77,77));
        logout.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        logout.setBackground(Color.BLACK);
    }//GEN-LAST:event_logoutMouseExited

    private void menuGuruMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuGuruMouseEntered
        // TODO add your handling code here:
        menuGuru.setBackground(new Color(255,51,51));
        menuGuru.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuGuruMouseEntered

    private void menuGuruMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuGuruMouseExited
        // TODO add your handling code here:
        menuGuru.setBackground(Color.WHITE);
    }//GEN-LAST:event_menuGuruMouseExited

    private void menuSiswaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSiswaMouseEntered
        // TODO add your handling code here:
        menuSiswa.setBackground(new Color(255,51,51));
        menuSiswa.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuSiswaMouseEntered

    private void menuSiswaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSiswaMouseExited
        // TODO add your handling code here:
        menuSiswa.setBackground(Color.WHITE);
    }//GEN-LAST:event_menuSiswaMouseExited

    private void menuKelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuKelasMouseEntered
        // TODO add your handling code here:
        menuKelas.setBackground(new Color(255,51,51));
        menuKelas.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuKelasMouseEntered

    private void menuKelasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuKelasMouseExited
        // TODO add your handling code here:
        menuKelas.setBackground(Color.WHITE);
    }//GEN-LAST:event_menuKelasMouseExited

    private void menuPelajaranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPelajaranMouseEntered
        // TODO add your handling code here:
        menuPelajaran.setBackground(new Color(255,51,51));
        menuPelajaran.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuPelajaranMouseEntered

    private void menuPelajaranMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPelajaranMouseExited
        // TODO add your handling code here:
        menuPelajaran.setBackground(Color.WHITE);
    }//GEN-LAST:event_menuPelajaranMouseExited

    private void menuAbsenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAbsenMouseEntered
        // TODO add your handling code here:
        menuAbsen.setBackground(new Color(255,51,51));
        menuAbsen.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuAbsenMouseEntered

    private void menuAbsenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAbsenMouseExited
        // TODO add your handling code here:
        menuAbsen.setBackground(Color.WHITE);
    }//GEN-LAST:event_menuAbsenMouseExited

    private void menuNilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuNilaiMouseClicked
        // TODO add your handling code here:
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();
        
        //add Panel, add panel dari Guru.Java (sebuah panel)
        Pane.add(new Transaksi.Nilai());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_menuNilaiMouseClicked

    private void menuNilaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuNilaiMouseEntered
        // TODO add your handling code here:
        menuNilai.setBackground(new Color(255,51,51));
        menuNilai.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuNilaiMouseEntered

    private void menuNilaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuNilaiMouseExited
        // TODO add your handling code here:
        menuNilai.setBackground(Color.WHITE);
    }//GEN-LAST:event_menuNilaiMouseExited

    private void formAbsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formAbsenActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
   
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();
        
        //add Panel, add panel dari Guru.Java (sebuah panel)        
        Pane.add(new Absen());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_formAbsenActionPerformed

    private void transNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transNilaiActionPerformed
        // TODO add your handling code here:
   
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();
        
        //add Panel, add panel dari Guru.Java (sebuah panel)        
        Pane.add(new Transaksi.Nilai());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_transNilaiActionPerformed

    private void menuReportGuruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportGuruMouseClicked
        // TODO add your handling code here:
        try{
            String namaFile = "src/Laporan/ReportGuru.jasper";
            HashMap parameter = new HashMap();
            File report_file = new File(namaFile);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
            JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_menuReportGuruMouseClicked

    private void menuReportGuruMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportGuruMouseEntered
        // TODO add your handling code here:
        menuReportGuru.setBackground(new Color(255,51,51));
        menuReportGuru.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuReportGuruMouseEntered

    private void menuReportGuruMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportGuruMouseExited
        // TODO add your handling code here:
        menuReportGuru.setBackground(Color.WHITE);
    }//GEN-LAST:event_menuReportGuruMouseExited

    private void menuReportSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportSiswaMouseClicked
        // TODO add your handling code here:
        try{
            String namaFile = "src/Laporan/ReportSiswa.jasper";
            HashMap parameter = new HashMap();
            File report_file = new File(namaFile);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
            JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_menuReportSiswaMouseClicked

    private void menuReportSiswaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportSiswaMouseEntered
       // TODO add your handling code here:
        menuReportSiswa.setBackground(new Color(255,51,51));
        menuReportSiswa.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuReportSiswaMouseEntered

    private void menuReportSiswaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportSiswaMouseExited
        // TODO add your handling code here:
        menuReportSiswa.setBackground(Color.WHITE);
    }//GEN-LAST:event_menuReportSiswaMouseExited

    private void menuReportAbsenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportAbsenMouseClicked
        // TODO add your handling code here:
        try{
            String namaFile = "src/Laporan/ReportAbsen.jasper";
            HashMap parameter = new HashMap();
            File report_file = new File(namaFile);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
            JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_menuReportAbsenMouseClicked

    private void menuReportAbsenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportAbsenMouseEntered
        // TODO add your handling code here:
        menuReportAbsen.setBackground(new Color(255,51,51));
        menuReportAbsen.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuReportAbsenMouseEntered

    private void menuReportAbsenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportAbsenMouseExited
        // TODO add your handling code here:
        menuReportAbsen.setBackground(Color.WHITE);
    }//GEN-LAST:event_menuReportAbsenMouseExited

    private void menuReportPelajaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportPelajaranMouseClicked
        // TODO add your handling code here:
        try{
            String namaFile = "src/Laporan/ReportMataPelajaran.jasper";
            HashMap parameter = new HashMap();
            File report_file = new File(namaFile);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
            JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_menuReportPelajaranMouseClicked

    private void menuReportPelajaranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportPelajaranMouseEntered
        // TODO add your handling code here:
        menuReportPelajaran.setBackground(new Color(255,51,51));
        menuReportPelajaran.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuReportPelajaranMouseEntered

    private void menuReportPelajaranMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportPelajaranMouseExited
        // TODO add your handling code here:
        menuReportPelajaran.setBackground(Color.WHITE);
    }//GEN-LAST:event_menuReportPelajaranMouseExited

    private void menuReportNilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportNilaiMouseClicked
        // TODO add your handling code here:
        try{
            String namaFile = "src/Laporan/ReportNilai.jasper";
            HashMap parameter = new HashMap();
            File report_file = new File(namaFile);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
            JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_menuReportNilaiMouseClicked

    private void menuReportNilaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportNilaiMouseEntered
        // TODO add your handling code here:
        menuReportNilai.setBackground(new Color(255,51,51));
        menuReportNilai.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuReportNilaiMouseEntered

    private void menuReportNilaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportNilaiMouseExited
        // TODO add your handling code here:
        menuReportNilai.setBackground(Color.WHITE);
    }//GEN-LAST:event_menuReportNilaiMouseExited
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Laporan;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel MenuLogo;
    private javax.swing.JPanel Pane;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JPanel PanelDashboard;
    private javax.swing.JMenu Transaksi;
    private javax.swing.JLabel clock;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel form;
    private javax.swing.JMenuItem formAbsen;
    private javax.swing.JMenuItem formGuru;
    private javax.swing.JMenuItem formKelas;
    private javax.swing.JMenuItem formPelajaran;
    private javax.swing.JMenuItem formSiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel laporan;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logout;
    private javax.swing.JMenu mMaster;
    private javax.swing.JLabel menuAbsen;
    private javax.swing.JLabel menuGuru;
    private javax.swing.JLabel menuKelas;
    private javax.swing.JLabel menuNilai;
    private javax.swing.JLabel menuPelajaran;
    private javax.swing.JLabel menuReportAbsen;
    private javax.swing.JLabel menuReportGuru;
    private javax.swing.JLabel menuReportNilai;
    private javax.swing.JLabel menuReportPelajaran;
    private javax.swing.JLabel menuReportSiswa;
    private javax.swing.JLabel menuSiswa;
    private javax.swing.JPanel slideMenuForm;
    private javax.swing.JPanel slideMenuLaporan;
    private javax.swing.JPanel slideMenuTransaksi;
    private javax.swing.JLabel tanggal;
    private javax.swing.JMenuItem transNilai;
    private javax.swing.JLabel transaksi;
    // End of variables declaration//GEN-END:variables
}
